apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-spring-svc
  labels:
    app: {{.Release.Name}}-spring-svc
spec:
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: {{ include "spring.deploymentLabel" . }}
  type: ClusterIP
