apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      application: hello

  template:
    metadata:
      labels:
        application: hello
    spec:
      containers:
        - name: hello-go
          image: gauravagarwalr/hello-go
