apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      application: hello

  template:
    labels:
      application: hello
    spec:
      containers:
        - name: hello-go
          image: gauravagarwalr/hello-go
