apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-demo-cm
data:
  some-key: some-value
  files: {{.Files.Get "secret.key"}}
  # IsBetaSupported: {{.Capabilities.APIVersions.Has "apps/v1"}}
  k8sVersion: {{.Capabilities.KubeVersion}}
  k8sVersionVersion: {{.Capabilities.KubeVersion.Version}}
  helmVersion: {{ quote .Capabilities.HelmVersion.Version }}
  goTemplate: {{ quote .Capabilities.HelmVersion.GoVersion }}
  # (or)
  values: {{ quote .Values }}
  languages: {{ quote .Values.languages }}
  # favourite: {{default "Green" .Values.favourite }}
  favourite: {{ .Values.languages | default (list "Spice" "Sugar") | first | default "Green" }}
  class: {{quote .Values.class}}
  classCount: "{{.Values.count}}"
  things: {{ quote .Values.things }}
  portNumber: {{.Values.port | quote}}
  someJSON: {{.Values.someJSON|quote }}
  # configMaps: {{/* lookup "v1" "ConfigMap" "default" "" | quote */}}
  configMapCount: {{ (lookup "v1" "ConfigMap" "default" "").items | len | quote }}
  cmLabels: {{ ((lookup "v1" "ConfigMap" "default" "").items | first).metadata.labels | quote }}
