apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "hook-demo.fullname" . }}-pre-install"
  labels:
    {{- include "hook-demo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  containers:
    - name: wget
      image: busybox
      command: ['echo']
      args: ['Running pre-install checks...']
  restartPolicy: Never
